const jokes = {
  b: [
    "După prea multe pahare și priviri prelungi,",
    "La o petrecere în care lumina s-a stins complet,",
    "Într-o noapte în care flirtul era sport național,",
    "Când cineva a spus că „e doar o glumă”,",
    "Când conversația a început să devină prea caldă,",
    "După ce cineva a atins un subiect prea tentant,",
    "Într-un moment în care distanțele s-au micșorat suspect,",
    "Când muzica a devenit prea incitantă,",
    "După ce cineva a zis „nu fi timid”,",
    "Când aerul era deja prea încărcat,",
    "La o întâlnire care a scăpat de sub control,",
    "Când zâmbetele au început să însemne mai mult,",
    "După ce cineva a luat prea în serios „te provoc”,",
    "Într-o seară în care regulile s-au evaporat,",
    "Când toată lumea a închis ochii la evidență,",
    "După ce alcoolul a dat curaj prostesc,",
    "Când gluma cu „suntem maturi” a murit rapid,",
    "Într-o pauză care a durat prea mult,",
    "După ce cineva a spus „jur că nu spun nimănui”,",
    "Când căldura din cameră n-a mai fost doar de la calorifer,",
    "Într-un moment în care nimeni n-a mai vrut să plece acasă,",
    "Când discuția a trecut de la amuzant la dubios,",
    "După ce privirile au devenit prea insistente,",
    "Într-o seară care sigur nu trebuia povestită,",
      "După ce cineva a zis «stai să-ți arăt ceva»,",
  "Când gluma a început să sune ca o invitație,",
  "După un «hai că nu mușc»,",
  "Când apropierea n-a mai fost accidentală,",
  "După ce cineva a verificat dacă ușa e încuiată,",
  "Când s-a făcut brusc prea liniște,",
  "După un zâmbet care promitea belele,",
  "Când cineva a spus «doar între noi»,",
  "După ce spațiul personal a devenit opțional,",
  "Când nimeni n-a mai stat jos,",
  "După ce aerul a devenit suspect de fierbinte,",
  "Când un «nu știu» a sunat ca un «da»,",
  "După ce cineva a zis «n-ar trebui, dar…»,",
  "Când noțiunea de rușine a ieșit la țigară,",
  "După ce s-a făcut contact vizual prea lung,"
  ],
  m: [
    "lucrurile au început să se atingă mai mult decât voiai,",
    "cineva a început să șoptească chestii prea picante,",
    "o atingere a rămas mult prea aproape de limită,",
    "privirile au început să vorbească de-a dreptul,",
    "pașii s-au apropiat mai mult decât prietenia permitea,",
    "glumele au degenerat în flirt sincer,",
    "toți au început să se uite mult prea atent,",
    "secretele au început să iasă la iveală pe șoapte,",
    "atmosfera a devenit irezistibil de tentantă,",
    "cineva a dat primul pas mai repede decât trebuia,",
    "zâmbetele au devenit mai… năstrușnice,",
    "atingerile au început să zboare prea liber,",
    "cuvintele au început să miroasă a dorință,",
    "ochii nu s-au mai putut abține de la… explorare,",
    "limitele au fost tratate ca simple sugestii,",
    "cineva a explicat ceva folosind mâinile prea mult,",
    "tăcerile au devenit suspect de încărcate,",
    "respirațiile au început să se sincronizeze dubios,",
    "cineva a stat mult prea aproape fără motiv,",
    "o demonstrație „nevinovată” a durat cam mult,",
    "flirtul a devenit mult prea direct,",
    "toată lumea a realizat că e deja prea târziu,",
    "cineva a zâmbit fix când nu trebuia,",
    "o replică a schimbat complet dinamica,",
      "gluma a devenit al naibii de serioasă,",
  "atingerile n-au mai părut deloc accidentale,",
  "cineva a uitat complet de autocontrol,",
  "flirtul a trecut într-o zonă riscantă,",
  "replicile au devenit obraznic de directe,",
  "s-a testat o limită care nu trebuia testată,",
  "respirațiile au devenit mult prea apropiate,",
  "cineva a zâmbit exact când nu trebuia,",
  "tăcerile au început să spună lucruri murdare,",
  "gesturile au început să spună mai mult decât cuvintele,",
  "s-a intrat pe un teritoriu foarte alunecos,",
  "cineva a demonstrat ceva… cam lent,",
  "atenția s-a mutat clar unde nu trebuia,",
  "flirtul a devenit fără echivoc,",
  "toată lumea a realizat că asta scapă de sub control,"
  ],
  e: [
    "și dimineața toată lumea a evitat privirile directe.",
    "iar amintirile au devenit selective și cam roșii.",
    "și toată lumea a început să râdă nervos.",
    "iar conversațiile au devenit brusc foarte inocente.",
    "și toată lumea a căutat un subiect mai… puțin fierbinte.",
    "iar tăcerea a vorbit mai mult decât cuvintele.",
    "și toată lumea s-a prefăcut că nu s-a întâmplat nimic.",
    "iar ochii s-au ferit de orice contact vizual prelungit.",
    "și fiecare s-a gândit „nu pot crede că am zis asta”.",
    "iar glumele despre „ce s-a întâmplat” au început imediat.",
    "și toți s-au prefăcut că totul e doar o legendă urbană.",
    "iar rutina de a doua zi a fost plină de evitări elegante.",
    "și nimeni n-a mai privit la fel cina de pizza din seara aia.",
    "iar dimineața s-a simțit mult prea… jenantă.",
    "și nimeni n-a mai pomenit vreodată seara aia.",
    "iar grupul de WhatsApp a devenit brusc mai tăcut.",
    "și toți au realizat că a fost o idee proastă.",
    "iar rușinea a rămas în aer câteva zile.",
    "și nimeni n-a mai stat lângă nimeni la următoarea petrecere.",
    "iar râsul a fost clar un mecanism de apărare.",
    "și s-a stabilit tacit să nu se mai repete.",
    "iar privirile au devenit strict profesionale.",
    "și povestea a fost schimbată de fiecare dată.",
    "iar adevărul a fost îngropat definitiv.",
      "și toți au fost de acord să nu mai aducă vorba.",
  "iar rușinea a venit la pachet cu mahmureala.",
  "și nimeni n-a mai stat confortabil pe scaun.",
  "iar dimineața a fost plină de regrete tăcute.",
  "și nimeni n-a mai făcut glume pe tema asta.",
  "iar evitările au fost mai clare decât explicațiile.",
  "și toată lumea a realizat că a mers prea departe.",
  "iar subiectul a fost declarat tabu definitiv.",
  "și nimeni n-a mai pomenit numele nimănui.",
  "iar tăcerea a devenit regula de aur.",
  "și toți au înțeles că n-a fost cea mai bună idee.",
  "iar privirile au devenit suspect de prudente.",
  "și nimeni n-a mai propus jocuri data viitoare.",
  "iar atmosfera a murit instant.",
  "și toți s-au prefăcut că n-au memorie."
  ]
};
