const jokes = {
  b: [
    "Un hamster a apăsat pe butonul greșit,",
    "Un porumb a început să vorbească,",
    "Un copil a levitat fără explicație,",
    "Un toaster a prins conștiință,",
    "Un vecin a apărut dintr-o dimensiune paralelă,",
    "Un pește a cerut azil politic,",
    "Un papuc a fost ales lider,",
    "Un frigider a refuzat să mai răcească,",
      "Un cartof a cerut un interviu oficial,",
  "O șosetă a devenit conștientă de sine,",
  "Un semafor a început să plângă,",
  "Un copil a depus o plângere împotriva gravitației,",
  "Un câine a început să țină un discurs motivațional,",
  "O ușă a refuzat să mai fie deschisă,",
  "Un nor a cerut intimitate,",
  "Un pix a decis că nu mai scrie minciuni,",
  "Un scaun a pretins că e ocupat,",
  "Un bec a avut o revelație existențială,",
  "Un pește a sunat la poliție,",
  "Un calendar a sărit direct la joi,",
  "O oglindă a refuzat să mai reflecte realitatea,",
  "Un telefon a început să respire greu,",
  "O pisică a cerut drept de vot,",
  "Un lift a decis să meargă doar în jos,",
  "Un sandwich a cerut respect,",
  "Un copac a început să dea sfaturi financiare,",
  "Un pantof a fost declarat obiect sacru,",
  "Un aspirator a amenințat cu demisia,",
  "Un noroi a devenit influencer,",
  "Un ceas a refuzat să mai măsoare timpul,",
  "Un porumb a fost promovat manager,",
  "Un calculator a început să viseze,"
  ],
  m: [
    "iar realitatea s-a rupt puțin,",
    "în timp ce toată lumea aplauda,",
    "și o voce a șoptit ceva dubios,",
    "iar legile fizicii au făcut pauză,",
    "în timp ce nimeni nu părea surprins,",
    "iar timpul a tușit stânjenit,",
    "și gravitația a ezitat,",
    "într-un mod extrem de suspect,",
      "iar realitatea a oftat obosită,",
  "în timp ce nimeni n-a reacționat corect,",
  "și ceva important a fost ignorat complet,",
  "iar logica a ieșit la țigară,",
  "într-un mod care părea perfect rezonabil,",
  "iar bunul simț a fost pus pe mute,",
  "și totul a fost explicat foarte prost,",
  "în timp ce toată lumea a dat din cap,",
  "iar universul a părut confuz,",
  "și cineva a spus «are sens»,",
  "în timp ce nimeni nu asculta,",
  "iar explicația a fost prea lungă și inutilă,",
  "și realitatea a clipit de două ori,",
  "în timp ce haosul completa formulare,",
  "iar legile naturii au cerut o pauză,",
  "și nimeni n-a considerat asta ciudat,",
  "într-un consens absolut greșit,",
  "iar cineva a notat totul foarte serios,",
  "și situația a fost analizată excesiv,",
  "în timp ce absurdul era normalizat,",
  "iar întrebările au fost amânate,",
  "și explicația oficială n-a explicat nimic,",
  "în timp ce sensul dispărea lent,",
  "iar realitatea părea jenată,"
  ],
  e: [
    "apoi totul a fost considerat normal.",
    "și nimeni n-a întrebat de ce.",
    "după care s-a tăiat curentul.",
    "iar explicațiile au dispărut.",
    "și universul a ignorat incidentul.",
    "apoi realitatea a dat restart.",
    "și nimeni n-a clipit.",
    "iar povestea a fost uitată instant.",
      "și totul a fost trecut la evenimente minore.",
  "iar nimeni n-a simțit nevoia de explicații.",
  "și s-a decis că e prea târziu pentru întrebări.",
  "iar realitatea a continuat ca și cum nimic nu s-ar fi întâmplat.",
  "și incidentul a fost considerat irelevant.",
  "iar toată lumea a mers mai departe.",
  "și nimeni n-a fost surprins în mod real.",
  "iar situația a fost acceptată tacit.",
  "și universul a făcut pe prostul.",
  "iar explicația a fost pierdută definitiv.",
  "și nimeni n-a mai adus vorba.",
  "iar totul a devenit parte din rutină.",
  "și realitatea a închis ochii.",
  "iar incidentul n-a fost documentat.",
  "și toată lumea a fost de acord fără motiv.",
  "iar lucrurile au fost lăsate așa.",
  "și nimeni n-a avut obiecții.",
  "iar normalitatea a fost redefinită.",
  "și nimeni n-a cerut clarificări.",
  "iar povestea s-a terminat fără concluzie.",
  "și universul a schimbat subiectul.",
  "iar nimeni n-a clipit.",
  "și absurdul a fost declarat oficial normal.",
  "iar realitatea a mers mai departe."
  ]
};
