const jokes = {
  b: [
    "Într-o zi absolut normală,",
    "La școală, într-o pauză banală,",
    "Într-un oraș liniștit de provincie,",
    "Într-o dimineață în care cafeaua n-a ajutat,",
    "Într-o ședință care putea fi un email,",
    "Într-o garsonieră cu termopane noi,",
    "Într-o coadă infinită la ghișeu,",
    "Într-o zi de luni suspect de calmă,",
      "Într-o după-amiază fără niciun eveniment special,",
  "Într-o zi în care nimic interesant nu trebuia să se întâmple,",
  "La muncă, fix înainte de pauza de masă,",
  "Într-un open space cu prea multă liniște,",
  "Într-o sală de clasă prea caldă,",
  "Într-o zi de vineri care părea promițătoare,",
  "Într-un birou cu aer condiționat dubios,",
  "Într-o dimineață în care totul mergea conform planului,",
  "Într-o discuție aparent inofensivă,",
  "Într-un cartier unde nu se întâmplă nimic,",
  "La o masă de familie fără subiecte interesante,",
  "Într-o pauză de cafea prea scurtă,",
  "Într-un meeting care a început cu întârziere,",
  "Într-o zi în care internetul a mers prost,",
  "Într-o situație complet previzibilă,",
  "Într-o conversație de complezență,",
  "Într-un autobuz care a venit prea devreme,",
  "Într-o zi în care nimeni n-avea chef,",
  "Într-un moment lipsit de entuziasm,",
  "Într-o zi în care nimeni n-a citit agenda,"
  ],
  m: [
    "toată lumea a realizat că ceva nu e în regulă,",
    "profesorul a zâmbit ciudat,",
    "cineva a pus o întrebare greșită,",
    "șeful a spus că suntem o familie,",
    "nimeni nu știa ce se întâmplă exact,",
    "un coleg a început să explice prea mult,",
    "toți au dat din cap fără să înțeleagă,",
    "cineva a zis «lasă că merge și-așa»,",
      "cineva a făcut o observație inutilă,",
  "toată lumea a fost de acord din reflex,",
  "o explicație a devenit mult prea complicată,",
  "cineva a încercat să fie productiv,",
  "discuția a deviat ușor de la subiect,",
  "nimeni n-a vrut să fie primul care vorbește,",
  "cineva a repetat ce spusese deja altcineva,",
  "toți au pretins că au înțeles,",
  "o problemă minoră a fost exagerată,",
  "cineva a propus o soluție evidentă,",
  "șeful a spus «revenim la asta»,",
  "profesorul a cerut liniște pentru a treia oară,",
  "cineva a verificat ora prea des,",
  "s-a făcut o pauză stânjenitoare,",
  "cineva a explicat ceva ce era deja clar,",
  "nimeni n-a avut o opinie fermă,",
  "discuția a fost amânată pe săptămâna viitoare,",
  "cineva a folosit un exemplu prost,",
  "toată lumea a dat din cap aprobator,",
  "cineva a întrebat ce urmează,"
  ],
  e: [
    "și nimeni n-a mai vorbit despre asta.",
    "iar situația s-a rezolvat de la sine.",
    "și asta a devenit noua normalitate.",
    "după care toată lumea a plecat acasă.",
    "iar explicația n-a mai contat.",
    "și nimeni n-a pus alte întrebări.",
    "iar concluzia a fost ambiguă.",
    "și ziua a continuat ca de obicei.",
      "și nimic important nu s-a schimbat.",
  "iar subiectul a fost abandonat rapid.",
  "și totul a fost uitat până a doua zi.",
  "iar lucrurile au mers înainte.",
  "și nimeni n-a tras vreo concluzie.",
  "iar situația a rămas neschimbată.",
  "și discuția s-a încheiat fără rezultat.",
  "iar problema a reapărut mai târziu.",
  "și toată lumea a trecut peste.",
  "iar nimeni n-a părut afectat.",
  "și ziua a continuat perfect banal.",
  "iar lucrurile au fost lăsate așa.",
  "și nimeni n-a mai adus vorba.",
  "iar totul a fost considerat rezolvat.",
  "și rutina a fost reluată imediat.",
  "iar concluzia a lipsit complet.",
  "și nimeni n-a simțit că lipsește ceva.",
  "iar discuția n-a dus nicăieri.",
  "și nimeni n-a fost surprins.",
  "iar viața a mers mai departe."
  ]
};
