const jokes = {
  b: [
    "Într-o noapte prea liniștită,",
    "Când nimeni nu se uita atent,",
    "Fix când speranța dispărea,",
    "Într-un moment prost ales,",
    "Într-o tăcere inconfortabilă,",
    "Când totul părea pierdut,",
    "Într-un colț ignorat al orașului,",
    "Într-o liniște care spunea prea mult,",
      "Într-o zi care a început prea normal,",
  "Când nimeni n-a pus întrebarea corectă,",
  "Fix înainte să fie prea târziu,",
  "Într-un moment în care nimeni n-a vrut adevărul,",
  "Când toată lumea a ales să ignore semnele,",
  "Într-o situație care cerea curaj,",
  "Când speranța părea doar o glumă proastă,",
  "Într-un context în care nimeni nu conta,",
  "Când liniștea a părut o soluție bună,",
  "Într-o seară în care nimeni n-a ascultat,",
  "Când s-a decis să nu se facă nimic,",
  "Într-un loc unde lucrurile dispar ușor,",
  "Când realitatea a fost prea incomodă,",
  "Într-un moment în care toți știau, dar nimeni nu spunea,",
  "Când s-a ales varianta cea mai ușoară,",
  "Într-o clipă de indiferență colectivă,",
  "Când empatia a lipsit complet,",
  "Într-o poveste care nu trebuia spusă,",
  "Când toată lumea a privit în altă parte,",
  "Într-o zi care n-a fost trecută în raport,",
  "Când nimeni n-a vrut să fie responsabil,",
  "Într-un moment tratat ca o statistică,",
  "Când s-a decis că nu merită efortul,",
  "Într-o tăcere acceptată prea ușor,"
  ],
  m: [
    "lucrurile au luat o întorsătură greșită,",
    "adevărul a ieșit la iveală,",
    "cineva a început să râdă încet,",
    "o decizie proastă a fost luată,",
    "nimeni n-a intervenit,",
    "consecințele au devenit inevitabile,",
    "ceva s-a rupt definitiv,",
    "iar intențiile reale au ieșit la suprafață,",
      "situația a degenerat fără zgomot,",
  "decizia greșită a părut logică atunci,",
  "cineva a înțeles prea târziu,",
  "lipsa de reacție a vorbit clar,",
  "toți au presupus că altcineva va interveni,",
  "adevărul a fost îngropat rapid,",
  "o alegere mică a avut urmări mari,",
  "nimeni n-a vrut să complice lucrurile,",
  "s-a ales confortul în locul binelui,",
  "responsabilitatea a fost pasată mai departe,",
  "cineva a râs ca să nu plângă,",
  "situația a fost tratată superficial,",
  "o scuză slabă a fost acceptată,",
  "toată lumea a mers mai departe,",
  "problema a fost amânată intenționat,",
  "consecințele au fost ignorate elegant,",
  "s-a decis că nu e treaba nimănui,",
  "o promisiune a fost uitată imediat,",
  "empatia a fost considerată opțională,",
  "totul a fost redus la un incident minor,",
  "cineva a ales să tacă definitiv,",
  "realitatea a fost reinterpretată convenabil,",
  "vina a fost diluată între toți,",
  "nimeni n-a vrut să fie primul care reacționează,"
  ],
  e: [
    "și nimeni n-a fost salvat.",
    "iar consecințele au rămas.",
    "și nimic n-a mai putut fi reparat.",
    "iar liniștea a devenit permanentă.",
    "și nimeni n-a fost tras la răspundere.",
    "iar totul s-a terminat acolo.",
    "și asta a fost sfârșitul.",
    "iar povestea n-a avut martori.",
      "și nimeni n-a mai vorbit despre asta.",
  "iar lucrurile au continuat ca și cum nimic nu s-ar fi întâmplat.",
  "și adevărul n-a mai contat.",
  "iar consecințele au fost acceptate în tăcere.",
  "și toată lumea a dormit liniștită după.",
  "iar povestea a fost clasată rapid.",
  "și nimeni n-a fost considerat vinovat.",
  "iar totul a devenit doar o amintire neplăcută.",
  "și subiectul a fost schimbat imediat.",
  "iar tăcerea a fost soluția oficială.",
  "și nimeni n-a învățat nimic.",
  "iar greșeala a fost repetată mai târziu.",
  "și cazul a fost uitat complet.",
  "iar lipsa de reacție a fost normalizată.",
  "și nimeni n-a cerut explicații.",
  "iar responsabilitatea a dispărut.",
  "și lucrurile n-au mai fost reparate.",
  "iar finalul n-a impresionat pe nimeni.",
  "și totul a fost trecut la pierderi acceptabile.",
  "iar istoria n-a consemnat nimic.",
  "și asta a fost considerată o încheiere.",
  "iar indiferența a câștigat.",
  "și nimeni n-a simțit nevoia de scuze.",
  "iar povestea s-a terminat fără concluzie."
]
};
